#!/bin/bash
echo "=============================="
echo "Environment script"
echo "=============================="
echo " "
echo "Jestes zalogowany jako $USER"
echo ""
echo "Twoja lokalizacja to: $PWD"
echo ""
echo "Twoj domowy katalog to $HOME"
echo ""
echo "Twoja zmienna PATH wyglada tak: $PATH"
echo ""
echo "=============================="